### PR TITLE
add contract auto gas

### PR DESCRIPTION
**Pull request by ypenghui6**
This change is [Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/58)

### CODE REVIEW

**Review by csquan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/58)* status: all files reviewed, 1 unresolved discussion (waiting on @ypenghui6)

___
*[libraries/chain/db_block.cpp, line 827 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/58#-M1c_QYb9c38sxGYz0p2:-M1c_QYb9c38sxGYz0p3:b-f9ckxy) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/1d926051962cdba275ed19369d9cd0eef3848664/libraries/chain/db_block.cpp#L827)):*
> ```
> call_contract_condition
> ```

**Review by csquan — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/58)* status: all files reviewed, 1 unresolved discussion (waiting on @ypenghui6)

**Review by ypenghui6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/58)* status: all files reviewed, 1 unresolved discussion (waiting on @csquan)

___
*[libraries/chain/db_block.cpp, line 827 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/58#-M1c_QYb9c38sxGYz0p2:-M1dW9aU4IXdF-315ohJ:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/1d926051962cdba275ed19369d9cd0eef3848664/libraries/chain/db_block.cpp#L827)):*
<details><summary><i>Previously, csquan wrote…</i></summary><blockquote>

> ```
> call_contract_condition
> ```

</blockquote></details>

Done.

**Review by csquan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/58)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
