### PR TITLE
add signidice arithmetic

### PR DESCRIPTION
**Pull request by ypenghui6**
1.Introducing RSA encryption
2.Added contract RSA encryption API
3.Added cli_wallet RSA encryption API

---
This change is [Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81)

### CODE REVIEW

**Review by wanliqun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81)* status: 0 of 11 files reviewed, 15 unresolved discussions (waiting on @ypenghui6)

___
*[libraries/chain/contract_authority.cpp, line 65 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3doN7gCiekppQ47428:-M3doN7gCiekppQ47429:byth3jd) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L65)):*
> ```cpp
> }
> 
> void register_scheduler::set_random_key( string d_str )
> ```

what you mean by d_str? Name it explicitly pls, also add some comments.
___
*[libraries/chain/contract_authority.cpp, line 70 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dqMJIBcNnKkV5TJCQ:-M3dqMJIBcNnKkV5TJCR:b2jus8n) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L70)):*
> ```cpp
>     {
>         std::string tmp_pub = d_str;
>         if(d_str.compare(0, GRAPHENE_RSA_PUBLIC_BEGIN_SIZE - 1, GRAPHENE_RSA_PUBLIC_BEGIN) == 0)
> ```

if GRAPHENE_RSA_PUBLIC_BEGIN defined as "-----BEGIN RSA PUBLIC KEY-----\n", shouldn't GRAPHENE_RSA_PUBLIC_BEGIN_SIZE be GRAPHENE_RSA_PUBLIC_BEGIN.size()?  Then why you minus 1 here?
___
*[libraries/chain/contract_authority.cpp, line 73 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dtqO3D-C8Co4JvNGR:-M3dtqO3D-C8Co4JvNGS:bf8ocvf) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L73)):*
> ```cpp
>         {
>             tmp_pub = tmp_pub.substr( GRAPHENE_RSA_PUBLIC_BEGIN_SIZE -1 );
>         }      
> ```

else you can assert & quit now as it's not valid RSA pubkey file?
___
*[libraries/chain/contract_authority.cpp, line 74 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3du7Yw1l6bs0FveJAY:-M3du7Yw1l6bs0FveJAZ:b-5l8sge) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L74)):*
> ```cpp
>             tmp_pub = tmp_pub.substr( GRAPHENE_RSA_PUBLIC_BEGIN_SIZE -1 );
>         }      
>         if(d_str.compare(d_str.length() - GRAPHENE_RSA_PUBLIC_END_SIZE + 1, d_str.length(), GRAPHENE_RSA_PUBLIC_END) == 0)
> ```

`GRAPHENE_RSA_PUBLIC_END_SIZE`

ditto, have another check  yourself.
___
*[libraries/chain/contract_authority.cpp, line 81 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dxtnh9WVODcon2ex9:-M3dxtnh9WVODcon2exA:b91g8dg) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L81)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         if(tmp_pub.find_first_of("\n") == 64)
>         {
>             for(unsigned int i = 64; i < tmp_pub.length(); i += 64)
>             {
>                 tmp_pub = tmp_pub.replace(i, 1, "");
>             }
>         }
> ```
</details>


how about using this to strip the end of line?
str.erase(std::remove(str.begin(), str.end(), '\n'), str.end());
___
*[libraries/chain/contract_authority.cpp, line 86 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e-zwqBQUjReiFcfqq:-M3e-zwqBQUjReiFcfqr:byzjcyu) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L86)):*
> ```
>         FC_ASSERT( tmp_pub.length() == 360, "Wrong public key ${pub_key_base64}", ("pub_key_base64", d_str) );
>         public_key_rsa_type rand_key(tmp_pub);
> ```
Considering check the validity of pub data inside public_key_rsa_type constructor by throwing an exception?
___
*[libraries/chain/contract_authority.cpp, line 87 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dxBMVCiEE2LVUzsad:-M3dxBMVCiEE2LVUzsae:b-r26a74) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L87)):*
> ```cpp
>         FC_ASSERT( tmp_pub.length() == 360, "Wrong public key ${pub_key_base64}", ("pub_key_base64", d_str) );
>         public_key_rsa_type rand_key(tmp_pub);
>         FC_ASSERT(is_owner(), "You`re not the contract`s owner");
> ```

Shouldn't this be asserted at the begining of this function?
___
*[libraries/chain/include/graphene/chain/protocol/types.hpp, line 356 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e2MVK1DBmsVyNg_9S:-M3e2MVLBdb39aD_wUFF:bsz4ao1) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/include/graphene/chain/protocol/types.hpp#L356)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     // TODO: This is temporary for testing
>     bool is_valid_v1(const std::string &base58str);
>     bool verify( string digest_str, string sig_str )const;
> };
> ```
</details>

Move this to your unit test ?
___
*[libraries/chain/protocol/types.cpp, line 36 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dyyys0rk4VFpuGgC9:-M3dyyys0rk4VFpuGgCA:b677llw) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/protocol/types.cpp#L36)):*
> ```cpp
>     public_key_rsa_type::public_key_rsa_type():key_data(){};
> 
>      public_key_rsa_type::public_key_rsa_type( const fc::bytes& data )
> ```

Wrong indent
___
*[libraries/chain/protocol/types.cpp, line 67 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e3PfDCcm-SNUTBCM3:-M3e3PfDCcm-SNUTBCM4:b-ppnr1f) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/protocol/types.cpp#L67)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>             std::string tmp_pub = base64str;
>             if(base64str.compare(0, GRAPHENE_RSA_PUBLIC_BEGIN_SIZE - 1, GRAPHENE_RSA_PUBLIC_BEGIN) == 0)
>             {
>                   tmp_pub = tmp_pub.substr( GRAPHENE_RSA_PUBLIC_BEGIN_SIZE -1 );
>             }
>             if(base64str.compare(base64str.length() - GRAPHENE_RSA_PUBLIC_END_SIZE + 1, base64str.length(), GRAPHENE_RSA_PUBLIC_END) == 0)
>             {
>                   tmp_pub = tmp_pub.substr(0, tmp_pub.length() - GRAPHENE_RSA_PUBLIC_END_SIZE);
>             }
>             if(tmp_pub.find_first_of("\n") == 64)
>             {
>                   for(unsigned int i = 64; i < tmp_pub.length(); i += 64)
>                   {
>                         tmp_pub = tmp_pub.replace(i, 1, "");
>                   }
>             }
> ```
</details>


ditto
___
*[libraries/wallet/wallet.cpp, line 3333 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e49zqCvg22PFsvjYZ:-M3e49zqCvg22PFsvjY_:b3hdn9g) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3333)):*
> ```cpp
>       pem += GRAPHENE_RSA_PRIVATE_END;
> 
>        result.wif_priv_key = pem;
> ```

wrong indent
___
*[libraries/wallet/wallet.cpp, line 3360 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4O_p374z3eMaQLlU:-M3e4O_p374z3eMaQLlV:b-fd1zom) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3360)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>              std::string tmp_pub = pub_key_base64;
>             if(pub_key_base64.compare(0, GRAPHENE_RSA_PUBLIC_BEGIN_SIZE - 1, GRAPHENE_RSA_PUBLIC_BEGIN) == 0)
>             {
>                   tmp_pub = tmp_pub.substr( GRAPHENE_RSA_PUBLIC_BEGIN_SIZE -1 );
>             }
>             if(pub_key_base64.compare(pub_key_base64.length() - GRAPHENE_RSA_PUBLIC_END_SIZE + 1, pub_key_base64.length(), GRAPHENE_RSA_PUBLIC_END) == 0)
>             {
>                   tmp_pub = tmp_pub.substr(0, tmp_pub.length() - GRAPHENE_RSA_PUBLIC_END_SIZE);
>             }
>             if(tmp_pub.find_first_of("\n") == 64)
>             {
>                   for(unsigned int i = 64; i < tmp_pub.length(); i += 64)
>                   {
>                         tmp_pub = tmp_pub.replace(i, 1, "");
>                   }
>             }
> ```
</details>


These codes has been repeated 3 times, try to refactor them in some function?
___
*[libraries/wallet/wallet.cpp, line 3373 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4dCZ59GiuH-OuWBR:-M3e4dCZ59GiuH-OuWBS:b-oj9fn6) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3373)):*
> ```cpp
>       catch( ... )
>       {
>           elog("Wrong public key ${pub_key_base64}, or digest ${digest_str}, or signature: ${sig_str}", ("pub_key_base64", pub_key_base64)("digest_str", digest_str)("sig_str", sig_str));
> ```

Too long in a line,  have some line wrap?
___
*[libraries/wallet/wallet.cpp, line 3388 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4qLq5HWD-G30Wzzc:-M3e4qLq5HWD-G30Wzzd:b3hdn9g) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3388)):*
> ```cpp
>             }
> 
>              std::string tmp_priv = priv_key;
> ```

wrong indent
___
*[libraries/wallet/wallet.cpp, line 3400 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4tlRDXcVEaIWVXcU:-M3e4tlRDXcVEaIWVXcV:br11o90) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3400)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>             if(priv_key.compare(0, GRAPHENE_RSA_PRIVATE_BEGIN_SIZE - 1, GRAPHENE_RSA_PRIVATE_BEGIN) == 0)
>             {
>                   tmp_priv = tmp_priv.substr( GRAPHENE_RSA_PRIVATE_BEGIN_SIZE -1 );
>             }
>             if(priv_key.compare(priv_key.length() - GRAPHENE_RSA_PRIVATE_END_SIZE + 1, priv_key.length(), GRAPHENE_RSA_PRIVATE_END) == 0)
>             {
>                   tmp_priv = tmp_priv.substr(0, tmp_priv.length() - GRAPHENE_RSA_PRIVATE_END_SIZE);
>             }
>             if(tmp_priv.find_first_of("\n") == 64)
>             {
>                   for(int i = 64; i < tmp_priv.length(); i += 64)
>                   {
>                         tmp_priv.replace(i, 1, "");
>                   }
>             }
> ```
</details>

Again?

**Review by ypenghui6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81)* status: 0 of 11 files reviewed, 15 unresolved discussions (waiting on @wanliqun)

___
*[libraries/chain/contract_authority.cpp, line 65 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3doN7gCiekppQ47428:-M3eamb_DYZFRz7GAXlr:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L65)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

what you mean by d_str? Name it explicitly pls, also add some comments.
</blockquote></details>

Done.
___
*[libraries/chain/contract_authority.cpp, line 70 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dqMJIBcNnKkV5TJCQ:-M3eanNb6BmZnpjUE-QR:b-6rfhhm) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L70)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

if GRAPHENE_RSA_PUBLIC_BEGIN defined as "-----BEGIN RSA PUBLIC KEY-----\n", shouldn't GRAPHENE_RSA_PUBLIC_BEGIN_SIZE be GRAPHENE_RSA_PUBLIC_BEGIN.size()?  Then why you minus 1 here?
</blockquote></details>

It's not a string
Begin with 0
___
*[libraries/chain/contract_authority.cpp, line 73 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dtqO3D-C8Co4JvNGR:-M3ebTWgAWSvoLYybjVX:bytm5o2) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L73)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

else you can assert & quit now as it's not valid RSA pubkey file?
</blockquote></details>

Just remove prefix suffix
___
*[libraries/chain/contract_authority.cpp, line 74 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3du7Yw1l6bs0FveJAY:-M3ebn5G8tOgJ4ATNwfW:b-3ij06f) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L74)):*
> ditto, have another check yourself.
ditto
___
*[libraries/chain/contract_authority.cpp, line 81 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dxtnh9WVODcon2ex9:-M3edGU7BJT4gOUx-WcT:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L81)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

> ```
>         if(tmp_pub.find_first_of("\n") == 64)
>         {
>             for(unsigned int i = 64; i < tmp_pub.length(); i += 64)
>             {
>                 tmp_pub = tmp_pub.replace(i, 1, "");
>             }
>         }
> ```

how about using this to strip the end of line?
str.erase(std::remove(str.begin(), str.end(), '\n'), str.end());
</blockquote></details>

Done.
___
*[libraries/chain/contract_authority.cpp, line 86 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e-zwqBQUjReiFcfqq:-M3ejACfCKcOotTuFKGP:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L86)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

> ```
>         FC_ASSERT( tmp_pub.length() == 360, "Wrong public key ${pub_key_base64}", ("pub_key_base64", d_str) );
>         public_key_rsa_type rand_key(tmp_pub);
> ```
Considering check the validity of pub data inside public_key_rsa_type constructor by throwing an exception?
</blockquote></details>

Done.
___
*[libraries/chain/contract_authority.cpp, line 87 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dxBMVCiEE2LVUzsad:-M3edzAP8TapZj9d9pgH:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/contract_authority.cpp#L87)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Shouldn't this be asserted at the begining of this function?
</blockquote></details>

Done.
___
*[libraries/chain/include/graphene/chain/protocol/types.hpp, line 356 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e2MVK1DBmsVyNg_9S:-M3eeflg3MhpgzB6yYjY:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/include/graphene/chain/protocol/types.hpp#L356)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

> ```
>     // TODO: This is temporary for testing
>     bool is_valid_v1(const std::string &base58str);
>     bool verify( string digest_str, string sig_str )const;
> };
> ```
Move this to your unit test ?
</blockquote></details>

Done.
___
*[libraries/chain/protocol/types.cpp, line 36 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3dyyys0rk4VFpuGgC9:-M3eeoefBL53i2Jc53P_:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/protocol/types.cpp#L36)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Wrong indent
</blockquote></details>

Done.
___
*[libraries/chain/protocol/types.cpp, line 67 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e3PfDCcm-SNUTBCM3:-M3efXM42tLthMiPC9JX:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/chain/protocol/types.cpp#L67)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

> ```
>             std::string tmp_pub = base64str;
>             if(base64str.compare(0, GRAPHENE_RSA_PUBLIC_BEGIN_SIZE - 1, GRAPHENE_RSA_PUBLIC_BEGIN) == 0)
>             {
>                   tmp_pub = tmp_pub.substr( GRAPHENE_RSA_PUBLIC_BEGIN_SIZE -1 );
>             }
>             if(base64str.compare(base64str.length() - GRAPHENE_RSA_PUBLIC_END_SIZE + 1, base64str.length(), GRAPHENE_RSA_PUBLIC_END) == 0)
>             {
>                   tmp_pub = tmp_pub.substr(0, tmp_pub.length() - GRAPHENE_RSA_PUBLIC_END_SIZE);
>             }
>             if(tmp_pub.find_first_of("\n") == 64)
>             {
>                   for(unsigned int i = 64; i < tmp_pub.length(); i += 64)
>                   {
>                         tmp_pub = tmp_pub.replace(i, 1, "");
>                   }
>             }
> ```

ditto
</blockquote></details>

Done.
___
*[libraries/wallet/wallet.cpp, line 3333 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e49zqCvg22PFsvjYZ:-M3efel-2HMxQivG9kc1:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3333)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

wrong indent
</blockquote></details>

Done.
___
*[libraries/wallet/wallet.cpp, line 3360 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4O_p374z3eMaQLlU:-M3efy6S3Bu-CXAC5fOE:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3360)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

> ```
>              std::string tmp_pub = pub_key_base64;
>             if(pub_key_base64.compare(0, GRAPHENE_RSA_PUBLIC_BEGIN_SIZE - 1, GRAPHENE_RSA_PUBLIC_BEGIN) == 0)
>             {
>                   tmp_pub = tmp_pub.substr( GRAPHENE_RSA_PUBLIC_BEGIN_SIZE -1 );
>             }
>             if(pub_key_base64.compare(pub_key_base64.length() - GRAPHENE_RSA_PUBLIC_END_SIZE + 1, pub_key_base64.length(), GRAPHENE_RSA_PUBLIC_END) == 0)
>             {
>                   tmp_pub = tmp_pub.substr(0, tmp_pub.length() - GRAPHENE_RSA_PUBLIC_END_SIZE);
>             }
>             if(tmp_pub.find_first_of("\n") == 64)
>             {
>                   for(unsigned int i = 64; i < tmp_pub.length(); i += 64)
>                   {
>                         tmp_pub = tmp_pub.replace(i, 1, "");
>                   }
>             }
> ```

These codes has been repeated 3 times, try to refactor them in some function?
</blockquote></details>

Done.
___
*[libraries/wallet/wallet.cpp, line 3373 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4dCZ59GiuH-OuWBR:-M3egH2g2V1c9pKChsSc:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3373)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Too long in a line,  have some line wrap?
</blockquote></details>

Done.
___
*[libraries/wallet/wallet.cpp, line 3388 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4qLq5HWD-G30Wzzc:-M3egR8U9lQdEI4-jHB4:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3388)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

wrong indent
</blockquote></details>

Done.
___
*[libraries/wallet/wallet.cpp, line 3400 at r1](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3e4tlRDXcVEaIWVXcU:-M3ege4wEN58CooYKenW:b-896fix) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/33d903caad5b43155d59b06c582d0b4d29d99822/libraries/wallet/wallet.cpp#L3400)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

> ```
>             if(priv_key.compare(0, GRAPHENE_RSA_PRIVATE_BEGIN_SIZE - 1, GRAPHENE_RSA_PRIVATE_BEGIN) == 0)
>             {
>                   tmp_priv = tmp_priv.substr( GRAPHENE_RSA_PRIVATE_BEGIN_SIZE -1 );
>             }
>             if(priv_key.compare(priv_key.length() - GRAPHENE_RSA_PRIVATE_END_SIZE + 1, priv_key.length(), GRAPHENE_RSA_PRIVATE_END) == 0)
>             {
>                   tmp_priv = tmp_priv.substr(0, tmp_priv.length() - GRAPHENE_RSA_PRIVATE_END_SIZE);
>             }
>             if(tmp_priv.find_first_of("\n") == 64)
>             {
>                   for(int i = 64; i < tmp_priv.length(); i += 64)
>                   {
>                         tmp_priv.replace(i, 1, "");
>                   }
>             }
> ```
Again?
</blockquote></details>

Done.

**Review by wanliqun — APPROVED** [review]
:lgtm:

> Reviewed 7 of 11 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-:-M3fDImFDXCPvzEb51pz:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @wanliqun)

**Review by csquan — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81)* status: all files reviewed, 14 unresolved discussions (waiting on @wanliqun and @ypenghui6)

___
*[libraries/wallet/include/graphene/wallet/wallet.hpp, line 1504 at r3](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3iVDR136kOrfRVUcXz:-M3iVDR136kOrfRVUcY-:b-jh3uef) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/c810e804edd6df06abdf7070ec78a8659ed7754a/libraries/wallet/include/graphene/wallet/wallet.hpp#L1504)):*
> ```
> (list_assets)(list_asset_restricted_objects)(asset_update_restricted_list)(import_key)(import_balance)(suggest_brain_key)(suggest_brain_address_key)(derive_owner_keys_from_brain_key)(register_account)(upgrade_account)(create_account_with_brain_key)(sell_asset)(sell)(buy)(borrow_asset)(cancel_order)(transfer)(transfer2)(get_transaction_id)(create_asset)(update_asset)(update_bitasset)(update_asset_feed_producers)(publish_asset_feed)(issue_asset)(get_asset)(get_bitasset_data)(reserve_asset)(global_settle_asset)(settle_asset)(bid_collateral)
> ```
___
*[libraries/wallet/include/graphene/wallet/wallet.hpp, line 1527 at r3](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/81#-M3iUyBn0sPSiLvtOfiA:-M3iUyBo961kLgqPLIx5:bbzmfy5) ([raw file](https://github.com/cocos-bcx/cocos-mainnet/blob/08e57410fb4e708aa6867769f9eab50a97bd905f/libraries/wallet/include/graphene/wallet/wallet.hpp#L1527)):*
> ```
> (list_assets)(list_asset_restricted_objects)(asset_update_restricted_list)(import_key)(import_balance)(suggest_brain_key)(suggest_rsa_key)(rsa_sig)(rsa_verify)(suggest_brain_address_key)(derive_owner_keys_from_brain_key)(register_account)(upgrade_account)(create_account_with_brain_key)(sell_asset)(sell)(buy)(borrow_asset)(cancel_order)(transfer)(transfer2)(get_transaction_id)(create_asset)(update_asset)(update_bitasset)(update_asset_feed_producers)(publish_asset_feed)(issue_asset)(get_asset)(get_bitasset_data)(reserve_asset)(global_settle_asset)(settle_asset)(bid_collateral)
> ```

**Pull request merged**
