### PR TITLE
20200115hf

### PR DESCRIPTION
**Pull request by csquan**
20200115hf，兼容之前的交易

---
This change is [Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28)

### CODE REVIEW

**Review by ypenghui6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @csquan)

*[a discussion](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28#-LycXut7CxnKcTlRn-ce:-LycXut7CxnKcTlRn-cf:bdzlmwg) (no related file):*
> ```
> database::pay_candidates
> ```
If change the code and start fn node, we can see the different data.

---

**Review by ypenghui6 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28)* status: all files reviewed, 1 unresolved discussion (waiting on @csquan)

**Comment by csquan** [comment]
*[a discussion](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28#-LycXut7CxnKcTlRn-ce:-LycZXTs1w42KpbwfI-F:bjn9w5n) (no related file):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

> ```
> database::pay_candidates
> ```
If change the code and start fn node, we can see the different data.
</blockquote></details>

we can makesure our network and parters code is right,other node chage code has no matter.
for example,A play for BP role,change code to cheat,so wrong tx can pass and broadcast.
but this block can not got consesus. Anymore,this is a good question.

---

**Review by csquan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28)* status: all files reviewed, 1 unresolved discussion (waiting on @ypenghui6)

*[a discussion](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28#-LycXut7CxnKcTlRn-ce:-LycbHXtDdBuc3F5f-Bz:b-896fix) (no related file):*
<details><summary><i>Previously, csquan wrote…</i></summary><blockquote>

we can makesure our network and parters code is right,other node chage code has no matter.
for example,A play for BP role,change code to cheat,so wrong tx can pass and broadcast.
but this block can not got consesus. Anymore,this is a good question.
</blockquote></details>

Done.

---

**Review by ypenghui6 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cocos-bcx/cocos-mainnet/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
